name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-native:
    name: Native Ubuntu Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make
    
    - name: Run all tests
      run: |
        make test || exit 1
    
    - name: Cleanup
      run: make clean

  test-docker:
    name: Docker Tests
    runs-on: ubuntu-latest
    if: false  # Отключено по умолчанию, можно включить при необходимости
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and test in Docker
      run: |
        docker build -t my-compiler-test .
        docker run --rm my-compiler-test
